#!/bin/bash

# backup original hosts file
cp /etc/hosts /etc/hosts.bak

# change localhost IP
echo "127.0.0.2 localhost" >> /etc/hosts

# change facebook.com IP
echo "8.8.8.8 facebook.com" >> /etc/hosts
