#!/bin/bash

# Get all network interfaces
interfaces=$(ifconfig | grep -o '^\w*')

# Loop through interfaces
for interface in $interfaces
do
  # Get IP address for each interface
  ip=$(ifconfig $interface | grep 'inet ' | awk '{print $2}')

  # Only display IPv4 IPs
  if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
    echo $ip
  fi
done

